#!/usr/bin/env python3
"""
Helper: compare downloaded wheel directory against the dependency specs
generated by offline_pack.sh (specs.txt).

Used by offline_pack.sh to detect which dependencies failed binary-only download.

Deliberately does NOT parse pyproject.toml (no tomllib/tomli dependency):
offline_pack.sh already resolved TOML into a plain-text specs file before
invoking this script, so it only needs to match package names against the
downloaded wheels. This keeps the script runnable on any Python >= 3.10,
even a bare interpreter without tomli installed.

Usage:
    python scripts/_check_missing.py <wheel_dir> <specs.txt>
    python scripts/_check_missing.py --list-missing <wheel_dir> <specs.txt>
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def parse_dep_name(spec: str) -> str:
    """Extract the package name from a PEP 508 dependency string."""
    # Remove extras, version specifiers, markers
    name = re.split(r"[>=<!~[;]", spec)[0].strip()
    return name.lower()


def load_dep_names(specs_path: str) -> list[str]:
    """Load dependency names from specs.txt (one package name per line)."""
    names: list[str] = []
    for line in Path(specs_path).read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            names.append(line)
    return names


def get_installed_wheel_names(wheel_dir: str) -> set[str]:
    """Get set of normalized package names from .whl files in a directory."""
    names: set[str] = set()
    for f in Path(wheel_dir).glob("*.whl"):
        # Wheel filename format: {distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl
        parts = f.name.split("-")
        if parts:
            names.add(parts[0].lower().replace("_", "-"))
    return names


def get_tar_gz_names(wheel_dir: str) -> set[str]:
    """Also check .tar.gz source archives as fallback."""
    names: set[str] = set()
    for f in Path(wheel_dir).glob("*.tar.gz"):
        parts = f.name.split("-")
        if parts:
            names.add(parts[0].lower().replace("_", "-"))
    return names


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("wheel_dir", help="Directory containing downloaded wheels")
    parser.add_argument("specs", help="Path to specs file (package names, one per line)")
    parser.add_argument(
        "--list-missing",
        action="store_true",
        help="Print missing package specs (one per line) instead of exit code",
    )
    args = parser.parse_args()

    dep_names = load_dep_names(args.specs)
    installed = get_installed_wheel_names(args.wheel_dir) | get_tar_gz_names(args.wheel_dir)

    missing: list[str] = []
    for dep in dep_names:
        pkg_name = parse_dep_name(dep)
        if pkg_name and pkg_name not in installed:
            missing.append(dep)

    if args.list_missing:
        for dep in missing:
            print(dep)
        return

    if missing:
        print(f"Missing packages: {', '.join(missing)}")
        sys.exit(1)
    else:
        print("All dependencies accounted for.")


if __name__ == "__main__":
    main()
